

# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

variables:
  - template: parameters.yml

stages:
- stage: Build AKS
  displayName: Build AKS
  jobs:
  - job: Build AKS
    displayName: Build AKS
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ variables.armconnection }}
        subscriptionId: ${{ variables.subid }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourcegrp }}
        location: 'Central US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.ArtifactStagingDirectory)/s/deployment/template.json'
        csmParametersFile: '$(Build.ArtifactStagingDirectory)/s/deployment/parametersFile.json'
        deploymentMode: 'Incremental'
        
