

trigger:
  - master

variables:
  - template: parameters.yml

stages:
- stage: Build AKS
  displayName: Build AKS
  jobs:
  - job: Build AKS
    displayName: Build AKS
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
        subscriptionId: ${{ variables.subscriptionId }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourceGroupName }}
        location: 'Central US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/s/template.json'
        csmParametersFile: '$(Pipeline.Workspace)/s/parametersFile.json'
        deploymentMode: 'Incremental'
        
