# Infrastructre deployement -AKS Cluster deploy

trigger:
  - main

variables:
  - template: parameters.yml

stages:
- stage: Build 
  displayName: Build 
  jobs:
  - job: Build 
    displayName: Build 
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: CopyFiles@2
        inputs:
          sourceFolder: 'deployment/'
          TargetFolder: '$(Pipeline.Workspace)'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ variables.rmconnection }}
        subscriptionId: ${{ variables.subscription }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourceGroup }}
        location: 'Central US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/s/deployment/template.json'
        csmParametersFile: '$(Pipeline.Workspace)/s/deployment/parametersFile.json'
        deploymentMode: 'Incremental'
        
